# -*- coding: utf-8 -*-
"""One-off migration: the old world into the Glasshouse record.

Sources:
  1. The old hub's D1 (mary-dashboard-db): crm_* tables -> new state tables
  2. data/jobs/*.md and data/companies/*.md -> position fields (the distilled
     memory the old system kept in files)
  3. data/frontdesk-state.json -> intake's seen list (so no old mail re-enters)
  4. data/mary-usage.jsonl -> usage rows (today's sessions, for the cost tab)

Deliberately DIRECT SQL into the new D1, not the API: the API has live side
effects (an issued quote spawns a chase task) that history must not re-fire.

  python core/migrate.py            # writes migration.sql and applies it
  python core/migrate.py --dry-run  # writes the SQL, applies nothing
"""
import argparse
import json
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import config

OLD_DASH = os.path.join(config.REPO, "attic", "dashboard")
HUB = os.path.join(config.REPO, "hub")
OUT_SQL = os.path.join(config.REPO, "test-results", "glasshouse", "migration.sql")
NO_WINDOW = getattr(subprocess, "CREATE_NO_WINDOW", 0)


def q(v):
    """SQL-quote one value."""
    if v is None or v == "":
        return "NULL"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def old_rows(table):
    p = subprocess.run(
        ["npx", "wrangler", "d1", "execute", "mary-dashboard-db", "--remote",
         "--json", "--command", "SELECT * FROM %s" % table],
        cwd=OLD_DASH, capture_output=True, text=True, timeout=180,
        shell=True, creationflags=NO_WINDOW)
    m = re.search(r"\[.*\]", p.stdout or "", re.S)
    if not m:
        print("  (no rows or no table: %s)" % table)
        return []
    try:
        payload = json.loads(m.group(0))
        return payload[0].get("results", []) if payload else []
    except (ValueError, IndexError, AttributeError):
        return []


def position_from_md(path, cap=7800):
    """The '## Position' section if the file has one, else the head of it."""
    try:
        text = open(path, encoding="utf-8").read()
    except IOError:
        return ""
    m = re.search(r"^##\s+(?:The\s+)?[Pp]osition.*?\n(.*?)(?=^##\s|\Z)", text,
                  re.S | re.M)
    body = (m.group(1) if m else "\n".join(text.splitlines()[:80])).strip()
    return body[:cap]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    sql = ["-- Glasshouse migration, generated by core/migrate.py"]

    # ---------------------------------------------------------- companies
    print("reading old CRM...")
    companies = old_rows("crm_company")
    rel_map = {"unknown": "prospect", "cold": "prospect", "known": "prospect"}
    for c in companies:
        pos = position_from_md(os.path.join(config.DATA, "companies", c["key"] + ".md"))
        sql.append(
            "INSERT OR REPLACE INTO company (key,name,relationship,lifetime_value,"
            "payment_terms,position,meta_json,created,updated,updated_by) VALUES "
            "(%s,%s,%s,%s,%s,%s,%s,%s,%s,'migration');"
            % (q(c["key"]), q(c["name"]),
               q(rel_map.get(c.get("relationship"), c.get("relationship") or "prospect")),
               q(c.get("lifetime_value") or None), q(c.get("payment_terms")),
               q(pos), q(json.dumps({"domains": json.loads(c.get("domains") or "[]"),
                                     "postcode": c.get("postcode") or ""})),
               q(c.get("created")), q(c.get("updated"))))
    print("  %d companies" % len(companies))

    contacts = old_rows("crm_contact")
    for c in contacts:
        sql.append(
            "INSERT OR IGNORE INTO contact (company_key,name,email,phone,role,notes) "
            "VALUES (%s,%s,%s,%s,%s,'');"
            % (q(c["company_key"]), q(c.get("name")), q(c.get("email")),
               q(c.get("phone")), q(c.get("role"))))
    print("  %d contacts" % len(contacts))

    # ---------------------------------------------------------- leads
    leads = old_rows("crm_lead")
    for l in leads:
        pos = position_from_md(os.path.join(config.DATA, "jobs", l["key"] + ".md"))
        outcome = {"no-decision": "dead"}.get(l.get("outcome"), l.get("outcome") or None)
        sql.append(
            "INSERT OR REPLACE INTO lead (key,company_key,title,stage,owner,value,"
            "deadline,award_due,next_action,next_action_date,outcome,position,"
            "meta_json,created,updated,updated_by) VALUES "
            "(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,'migration');"
            % (q(l["key"]), q(l.get("company_key") or "unknown"), q(l["title"]),
               q(l.get("stage") or "new"),
               q(l.get("owner") if l.get("owner") in config.PERSONAS else "mary"),
               q(l.get("value") or None), q(l.get("deadline")), q(l.get("award_due")),
               q(l.get("next_action")), q(l.get("next_action_date")), q(outcome),
               q(pos), q(json.dumps({"source": l.get("source") or "",
                                     "site": l.get("site") or "",
                                     "adminbase_ref": l.get("adminbase_ref") or ""})),
               q(l.get("created")), q(l.get("updated"))))
    print("  %d leads" % len(leads))

    # Jobs that exist as md files but never made the old CRM still deserve rows.
    known = {l["key"] for l in leads}
    jobs_dir = os.path.join(config.DATA, "jobs")
    extra = 0
    for f in sorted(os.listdir(jobs_dir)):
        key = f[:-3]
        if (not f.endswith(".md") or "archive" in f or key in known
                or key in ("README", "triage", "desk")):
            continue
        pos = position_from_md(os.path.join(jobs_dir, f))
        title = key.replace("-", " ").title()
        m = re.match(r"#\s+(.+)", open(os.path.join(jobs_dir, f), encoding="utf-8")
                     .readline() or "")
        if m:
            title = m.group(1).strip()[:150]
        sql.append(
            "INSERT OR IGNORE INTO lead (key,company_key,title,stage,owner,position,"
            "updated_by) VALUES (%s,'unknown',%s,'new','mary',%s,'migration');"
            % (q(key), q(title), q(pos)))
        extra += 1
    print("  %d job files without CRM rows" % extra)

    # ---------------------------------------------------------- quotes
    quotes = old_rows("crm_quote")
    st_map = {"to_check": "draft", "approved": "checked"}
    for r in quotes:
        sql.append(
            "INSERT OR IGNORE INTO quote (lead_key,revision,value,status,issued_at,"
            "basis,file_path) VALUES (%s,%s,%s,%s,%s,%s,%s);"
            % (q(r["lead_key"]), q(r.get("revision") or 1), q(r.get("value") or None),
               q(st_map.get(r.get("status"), r.get("status") or "draft")),
               q(r.get("issued_at")), q(r.get("basis")), q(r.get("document"))))
    print("  %d quotes" % len(quotes))

    # ---------------------------------------------------------- contracts + steps
    contracts = old_rows("crm_contract")
    for r in contracts:
        pos = position_from_md(os.path.join(config.DATA, "contracts", r["key"] + ".md"))
        sql.append(
            "INSERT OR REPLACE INTO contract (key,lead_key,company_key,title,po_ref,"
            "value,site_date,status,position,created,updated,updated_by) VALUES "
            "(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,'migration');"
            % (q(r["key"]), q(r.get("lead_key")), q(r.get("company_key") or "unknown"),
               q(r["title"]), q(r.get("po_ref")), q(r.get("value") or None),
               q(r.get("site_date")), q(r.get("status") or "live"), q(pos),
               q(r.get("created")), q(r.get("updated"))))
    print("  %d contracts" % len(contracts))

    STEP_ORDER = ["sign_off_po", "book_provisional", "submit_designs", "book_survey",
                  "order_frames", "order_glass", "send_rams", "arrange_labour",
                  "order_consumables", "confirm_bookings", "send_om", "invoice"]
    tasks = old_rows("crm_task")
    nsteps = 0
    counters = {}
    for t in tasks:
        if t.get("entity_type") != "contract":
            continue
        ck = t["entity_key"]
        n = (STEP_ORDER.index(t["step"]) + 1 if t.get("step") in STEP_ORDER
             else counters.setdefault(ck, 12) + 1)
        if t.get("step") not in STEP_ORDER:
            counters[ck] = n
        sql.append(
            "INSERT OR REPLACE INTO step (contract_key,n,label,detail,due,done_at,"
            "done_by) VALUES (%s,%s,%s,%s,%s,%s,%s);"
            % (q(ck), n, q(t.get("label") or t.get("step")), q(t.get("detail")),
               q(t.get("due")), q(t.get("done_at") or None), q(t.get("done_by"))))
        nsteps += 1
    print("  %d contract steps" % nsteps)

    # ---------------------------------------------------------- notes -> events
    notes = old_rows("crm_note")
    for n in notes:
        sql.append(
            "INSERT INTO event (ts,author,entity_type,entity_key,kind,body,ref) "
            "VALUES (%s,%s,%s,%s,'note',%s,%s);"
            % (q(n.get("created") or n.get("ts")), q(n.get("author") or "migration"),
               q(n.get("entity_type")), q(n.get("entity_key")),
               q(str(n.get("body") or "")[:4000]), q(n.get("source_ref"))))
    print("  %d notes -> events" % len(notes))

    # ---------------------------------------------------------- usage backfill
    n_usage = 0
    try:
        with open(os.path.join(config.DATA, "mary-usage.jsonl"), encoding="utf-8") as fh:
            for line in fh:
                try:
                    r = json.loads(line)
                except ValueError:
                    continue
                chat = r.get("chat", "")
                persona = chat.split(":")[0] if ":" in chat else "mary"
                entity = chat.split(":", 1)[1] if ":" in chat else chat
                sql.append(
                    "INSERT INTO usage (ts,persona,entity_key,session_id,model,calls,"
                    "context_tokens,output_tokens,seconds) VALUES "
                    "(%s,%s,%s,%s,'opus-legacy',%s,%s,%s,%s);"
                    % (q(r.get("at", "").replace("T", " ")), q(persona), q(entity),
                       q(r.get("session")), q(r.get("calls") or 0),
                       q(r.get("context_tokens") or 0), q(r.get("output_tokens") or 0),
                       q(r.get("seconds") or 0)))
                n_usage += 1
    except IOError:
        pass
    print("  %d usage rows" % n_usage)

    sql.append("INSERT INTO event (author,kind,body) VALUES "
               "('migration','note','Old system migrated into the Glasshouse record');")

    os.makedirs(os.path.dirname(OUT_SQL), exist_ok=True)
    with open(OUT_SQL, "w", encoding="utf-8") as fh:
        fh.write("\n".join(sql) + "\n")
    print("wrote %s (%d statements)" % (OUT_SQL, len(sql)))

    # ---------------------------------------------------------- intake seen ids
    try:
        with open(os.path.join(config.DATA, "frontdesk-state.json"), encoding="utf-8") as fh:
            seen = json.load(fh).get("seen", [])
        with open(os.path.join(config.DATA, "glasshouse-intake.json"), "w",
                  encoding="utf-8") as fh:
            json.dump({"seen": seen}, fh, indent=1)
        print("carried %d seen mail ids into intake state" % len(seen))
    except (IOError, ValueError) as e:
        print("no frontdesk state carried (%s)" % e)

    if a.dry_run:
        print("dry run - nothing applied")
        return 0
    p = subprocess.run(
        ["npx", "wrangler", "d1", "execute", "glasshouse-db", "--remote",
         "--file", OUT_SQL, "-y"],
        cwd=HUB, capture_output=True, text=True, timeout=600,
        shell=True, creationflags=NO_WINDOW)
    tail = (p.stdout or "").strip().splitlines()[-3:]
    print("\n".join(tail))
    if p.returncode != 0:
        print("APPLY FAILED:\n" + (p.stderr or "")[-1500:])
        return 1
    print("migration applied")
    return 0


if __name__ == "__main__":
    sys.exit(main())
