# -*- coding: utf-8 -*-
"""Assemble Mary's dashboard data and (optionally) deploy it.

Sources:
  data/dashboard-state.json          - curated by sessions at close-out
  Graph mary@ sentitems              - every email ever sent (live)
  test-results/mary-inbox/poller.log - poll/session counts
  HANDOVER.md 'no-action sessions'   - via state file

Usage:
  python scripts/mary_dashboard.py            # regenerate dashboard-data.js
  python scripts/mary_dashboard.py --deploy   # regenerate + wrangler deploy
"""
import argparse
import datetime as dt
import json
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mary_graph as mg

REPO = mg.REPO
STATE = os.path.join(REPO, "data", "dashboard-state.json")
OUT = os.path.join(REPO, "dashboard", "functions", "_data", "dashboard-data.js")
LOG = os.path.join(REPO, "test-results", "mary-inbox", "poller.log")


def sent_emails(token):
    st, res = mg.graph(token, "GET",
        "/users/%s/mailFolders/sentitems/messages?$top=50&$select=subject,toRecipients,sentDateTime,body&$orderby=sentDateTime%%20desc" % mg.MARY)
    if st != 200:
        return []
    out = []
    for m in res.get("value", []):
        out.append({
            "sent": m.get("sentDateTime", "")[:16].replace("T", " "),
            "to": ", ".join(r["emailAddress"]["address"].split("@")[0] for r in m.get("toRecipients", [])),
            "subject": m.get("subject", ""),
            "body": mg.html_to_text(m.get("body", {}).get("content", ""))[:6000],
        })
    return out


def inbox_seen():
    """Everything Mary has read: the processed queue records."""
    proc = os.path.join(REPO, "test-results", "mary-inbox", "processed")
    items = []
    if os.path.isdir(proc):
        for f in sorted(os.listdir(proc), reverse=True):
            if not f.endswith(".json"):
                continue
            try:
                d = json.load(open(os.path.join(proc, f), encoding="utf-8"))
            except Exception:
                continue
            items.append({
                "received": d.get("received", "")[:16].replace("T", " "),
                "from": d.get("from", ""),
                "subject": d.get("subject", ""),
                "attachments": len(d.get("attachments", [])),
                "body": (d.get("body") or "")[:5000],
            })
            if len(items) >= 80:
                break
    return items


def poller_stats():
    polls = launched = 0
    if os.path.exists(LOG):
        for line in open(LOG, encoding="utf-8", errors="replace"):
            if "poll done" in line:
                polls += 1
            if "launching Claude session" in line:
                launched += 1
    return polls, launched


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--deploy", action="store_true")
    args = ap.parse_args()

    state = json.load(open(STATE, encoding="utf-8"))
    env = mg.load_env()
    token = mg.get_token(env, "READER")
    emails = sent_emails(token)
    polls, launched = poller_stats()

    data = dict(state)
    data["updated"] = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    data["emails"] = emails
    data["inbox"] = inbox_seen()
    data["sessions"] = {
        "polls": polls,
        "launched": launched,
        "emailsSent": len(emails),
        "noAction": state.get("noActionSessions", []),
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// generated by scripts/mary_dashboard.py - do not edit\n")
        fh.write("export const DATA = %s;\n" % json.dumps(data, indent=1, ensure_ascii=False))
    print("wrote", OUT, "(%d jobs, %d requests, %d emails, %d inbox)" % (
        len(data["jobs"]), len(data.get("requests", [])), len(emails), len(data.get("inbox", []))))

    if args.deploy:
        r = subprocess.run(["npx.cmd", "wrangler", "pages", "deploy", "public", "--project-name", "mary-dashboard",
                            "--branch", "main", "--commit-dirty=true"],
                           cwd=os.path.join(REPO, "dashboard"), capture_output=True, text=True,
                           encoding="utf-8", errors="replace", timeout=600, shell=True)
        tail = (r.stdout + r.stderr)[-600:]
        print("deploy exit", r.returncode)
        print(tail)


if __name__ == "__main__":
    main()
